---
kind: pipeline
name: validate

steps:
  - name: prettier
    image: tmknom/prettier:latest
    commands:
      - prettier --check "./config/**/*.yaml"

  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

  - name: docker-compose
    image: tmaier/docker-compose:latest
    commands:
      - mv prd-${DRONE_REPO_NAME}-app.env.example prd-${DRONE_REPO_NAME}-app.env
      - docker-compose config -q

---
kind: pipeline
type: docker
name: test

steps:
  - name: latest
    image: esphome/esphome:latest
    pull: always
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - for file in $(find config -maxdepth 1 -type f -name "*.yaml" -not -name "secrets.yaml"); do esphome "$file" config; done

  - name: beta
    image: esphome/esphome:beta
    pull: always
    failure: ignore
    commands:
      - for file in $(find config -maxdepth 1 -type f -name "*.yaml" -not -name "secrets.yaml"); do esphome "$file" config; done

---
kind: pipeline
type: docker
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker-registry-username
      password:
        from_secret: docker-registry-password
      registry: docker-registry.theautomation.nl
      repo: docker-registry.theautomation.nl/coen/prd-${DRONE_REPO_NAME}-app
      auto_tag: true

---
kind: pipeline
type: docker
name: upgrade

depends_on:
  - validate
  - test

steps:
  - name: git pull
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/
        - git pull

  - name: docker compose up
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/
        - docker-compose up -d

  - name: compile and upload
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/config/
        - for file in $(find -maxdepth 1 -type f -name "*.yaml" -not -name "secrets.yaml"); do docker exec prd-esphome-app esphome "$file" run --no-logs; done

  - name: cleanup
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/
        - docker image prune -f
