---
kind: pipeline
name: validate

steps:
  - name: lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

  - name: docker-compose
    image: tmaier/docker-compose:latest
    commands:
      - mv prd-esphome-app.env.example prd-esphome-app.env
      - docker-compose config -q

---
kind: pipeline
name: test

steps:

  - name: beta
    image: esphome/esphome:beta
    pull: always
    failure: ignore
    entrypoint:
      - /bin/bash
    command:
      - find /config -maxdepth 1 -type f -name "*.yaml" -print0 | while IFS= read -r -d '' file ; do esphome "$file" config ; done

  - name: latest
    image: esphome/esphome:latest
    pull: always
    commands:
      - for file in *.yaml ; do esphome "$file" config ; done
