---
kind: pipeline
name: validate

steps:
  - name: lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

  - name: docker-compose
    image: tmaier/docker-compose:latest
    commands:
      - mv prd-esphome-app.env.example prd-esphome-app.env
      - docker-compose config -q

---
kind: pipeline
type: docker
name: test

steps:
  - name: latest
    image: esphome/esphome:latest
    pull: always
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - find /config -maxdepth 1 -name "*.yaml" -print0 | while read -d $'\0' file ; do esphome "$file" config ; done
