kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: esphome-secrets
  namespace: home-automation
spec:
  encryptedData:
    api_password: AgCHJxoVMFSvHuyAAjOYL74+PYt/LdIAqqlYbOey21rPObV8JN+4jNkATE9qwsgxIBDf2a4HiRUEZP8BOt49TuatNCZ/smArA9h3UOPPPz6bJFli3pJf59UcXtSVUQ+kYo8pIHPrD6VV3WKy4gjFwibC+X9Muf5XlNMseEs9ZjCHLfcIWg68ffuQM4m1lCNtpZ74UhVh7JcGKh2qOHKMS0olVMA3E3scPq48hVjMToouoxVMqwn+R1XoLa3rZiH+7dddXPozjQLl1ig7raqCxrSAlfREYcMwaTJcr6mT9B+MsRwVSje9JeHpVZSzO6Xu/+6bKhtrmJLnnTp4IA7xlOP7wLMO7NWg2C5lPNIUyrY3QZxuQ1sEpuY2kuz+dyjPVoXdfoZNnTbx3KXro/TKiymjgYrn9z0Z5tbjjmN6VM7z2YW1F+rHlcQ8RIDNGxPg42ATd9KHdnEDgdKkz/VyrVMB33fNU1u42iT5c7+c3wAqkyFgKZV7hxeB0bqCi6TAVgTz4ecyQjtV6RBvAAjqKGCzkmKafXjQ8rH2i8P+PC+TgrUDzNgWvUg2pLRFgYplYPCcIemkuvlYi+Lyn/8Q5EoqRcdtEE/WtSPsFiYc4azEn3tyTr03ZGTvXeSoOeGpmsNBHN59wZQqKV8qrLA0UL9EOsVjh6LGvgrScBhldWN1TcjFB2Xkto8vper1kwYuY8/+/A43p4pwI+jduwZJshyEYsF+
    ota_password: AgBbh1GzSwQxdSlO0SK8ku5Ufx9E01zDEp0jUDEJr0OK1NKWrf0ByZGUPzECOl4625VrFMwxGCeXs6H7lHEW9pW/JHGh3CRgbFb18vEbRuSOeWJetC+tlOyq934eIWgGMnsWIRwrYgIyAydjmUM8DgCabtp/cGelE2w9i6YoPpdiZzO2xbx09S0yY5612F2krkn9JQTFYsgsLo3X6N7PiY/KVYlu1paLB80EHP+10rVqwsHtkShXXM9tY1BK6yHJhxmcX8i0U0b65kByc8l1eN11D9yY0C4cL1m5lxYjmOGGgEiJcvRb8WFrpricl67mzVC2ldwj01jYHgZLBxR+ICZ1f8GRkgZcoTh+RICrWludU2CBypsbcArXxxoQONko65dcDgd4j7m04nd1iiVzRTukWej+akHaTnqfgjLAloJcxChntx4UTZEWfFtm7WzB2YxFrD81E0CGUJ23wbRXIKvlvIe+fQuiqvims65BZ+sjBEesKALfnvfWtwwodaVwSlMQD6c3tQE2aYnKWSHx9ADYlBaGhcL3CmJ6Uof8fu+FgSkHrz/DwcKPe1Kg1IwpxNjgv6foe0zobV/msBIFbt75lcT7hTpbOHpTaFv5adk5tT2T4KBHeOWl2LL5agCzzwntkxH1OzoWGrdAU33mSRCutR3otLNmBQuCzKgAK/ZWikQvqjkf0+iIlwY+K+APwcvxcIRgtrKcGOHeFTuCMBc=
    wifi_password: AgCox4s2ougUASK5iGwNQt4GGAFYkPIl4GasQjUxsXICginYztC86R4bJ6lyGPM6PNIJ9XSfkC71X9MpF9cVCXko9ar7RX3BxKp1qm5GLwK8JeVgqwOT2Wfu/JT3qJ5F94KK2F3nEvV2YGp6pSwewaYixDTzObd7VdCbpzTMTjLr3Phf9+/EtV8/IZD8mrVmawPNy0vEOMfvJ8c1/ZeswCzxC0b0Ny2HD6JhMOoAPnyVQ/mvRsvUD3FjB6/+wFDdrfRboZ+MHxf5sXJ3Ds4HRjKyyuy66YeRnDVC8D74MktXAjqZE3RaCNq5N3VXtRcdOIPe1tVIdzZ7gZ8+fGJ5bB5j8xKBrRdLHds1uyhuZGw9YV1x/7LC4CrCjnd7TMPM45QTvI0/t4bi+pBy+WoHM+G5Sgrp0jsDFgzG8ml5X0JA1hqwbr36hsPqMobE6LqgPsjMZ+rRnCRY0CjWwDE5lJnLbWyuX4sJsm3hXBhzI6CYl1l4hq3MEnTcnVQMMuztz9Fvc6hDDdBFmkNLBlwCtXQOSvzgbzkpMinkLrtwkmx3MJydKZcJhvdX04ycXdhroarIDDYLpD9imgWmFCrd4gowmeLEBwm0BwhteutQu+KjD2CYTxhDG3SAXuGkr65bDUzgCa97NxvrKnAZ5shVv1x/JLAWauDbv71cseYPzial77hDtVuMH9NLc/euEo1MvKoTk63IDaG6KoWtZEYYM8D7gELj
  template:
    data:
      secrets.yaml: |-
        wifi_ssid: WIFI-NOT
        wifi_password: "{{ index . "wifi_password" }}"
        wifi_domain: ".lan"
        api_password: "{{ index . "api_password" }}"
        ota_password: "{{ index . "ota_password" }}"
    metadata:
      name: secrets
      namespace: home-automation
      labels:
        app.kubernetes.io/name: esphome

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: esphome
  namespace: home-automation
  labels:
    app: esphome
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: esphome
          image: "container-image-registry.theautomation.nl/home-automation/esphome:latest@sha256:102a0af0a299bcf527dea24ef8422f991b47d474143db256fceb035173fb8051"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6052
              protocol: TCP
          env:
            - name: "ESPHOME_DASHBOARD_USE_PING"
              value: "true"
          livenessProbe:
            tcpSocket:
              port: 6052
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6052
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 6052
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
      volumes:
        - name: secrets
          secret:
            secretName: esphome-secrets
      imagePullSecrets:
        - name: container-image-registry-credentials

---
kind: Service
apiVersion: v1
metadata:
  name: esphome
  namespace: home-automation
  labels:
    app: esphome
  annotations:
spec:
  selector:
    app: esphome
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 6052
      targetPort: 6052

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: esphome
  namespace: home-automation
  labels:
    app: esphome
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx-private
  rules:
    - host: esphome.k8s.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: esphome
                port:
                  number: 6052
