kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: secrets
  namespace: home-automation
spec:
  encryptedData:
    api_password: AgCurqK7QEqFuC7niZFrPHM7wUizzz9Wlz3xutozQNHVFjZmmPy/jHKLIpcNRZ3kxT8g6ACNYWSj4ZAVFqTgjzUM8w9CTlxyRqfkhiIYTQNBPqtGAKMSCuNBPFDXjH2Q2/v21NSfp3dBDb1F3U2xQxv7LMy/8Wo7EkOBmRqVl+UyoP6XIM/FSk6fnpDaL6fuAx79s3R+VCp1Npib7lJ3BhVdNxj3gLG4luZ9M+fPVT9PXuWoK3eSQDtD+fbUICZ+CWMwKC0WFG6v+FGaFvnKbM13R4vCyg2tUtA5+/tohFBM1+poG1ohFprKgsbhSLVrjAeVUXzt8mJmLp6I6hgbQiLKY78KjMvgz7aJZJ/zaMKrlYmQ3pC+BkANTS1ELsaO4jZTts0Fn24U8dGBRdbKc4YDIcZsz7pkEoVykRJn9BwehpH6Ou05jick0lmNNMKJwBw/OyE1scls2OtEQX8Uwv2EljnbmpBj7MOqEiNVC9v5ILt/CwHTu2U6wn3NjEKXxG1L/32PNlcIBOlpWjm8KtR+cUBmM0ryT+18wVskjnO2tjLkMfS/vukqF38HTBKvxbTiIQ0OQDNRI1vDGjUYLtp54ChOlgSL4xvbZr8byyJ+9/nGJpQxKZDtnopgQkqXmoSCqd+15Cma1YKck533v+nF7Q5NZlkliSqJUNZ9muXCF5b5UJGS6ALNp+Gi+sq4LKxOZpUtHUy3rdpYZX41fzmnLnd1
    ota_password: AgCzwsyuow/9kRCZW2ga9NEBNE8543c8h4SqH0bey17stElCmXK0ddp4O5Evw6EQLvkq429RXuHbAQNhe0xqON7OSkhfL7eClsI6nr7pGr3/3O7i+ydZu8xWG9OwRE7ntr/Z+uuL61PH+BozK5pccYhVU5LS8ZnaqZg4cMEOvKq9VIHkYcYcWUa72AoERbflcixceuAho4EG+GImiEln7NOZ1+rGEDtaxxneAX2bpfGd/BbFx36n392hL1ftUz3GFCv7cJtfyHF6frPaK9a2HdkOutOjGm9b9CJYOtivYyqa+hGrpCS4uq0VqcUgMx2PHzUQWWAyHz3Jr/gIfokokX+LqpbaLvjax8KNPSvYI914wWx7ewhal5l5HTkLqlpUy7UhUl88ciyNSiXgCDneArUYMt+u9fbBuW3JaBj4iuHxLnf1EfyEHerYetvflpVQlXNHw9EAeBLzICDkq/zBvSv2YqV68N8vWT7WqK6dNxIx02kCKGVec+MauYBGgoOgiboBX4LJIxhWtNb1P5Hf/u4hv/ykLIX1487w9PRYTX6xaWOq8yRmT0Io5zcP/JHxbeOYJJB3C2fti2YwhA0tb2AFxxJgWsZwSAehlYq34goM0MFkgGIc01CAKzNBT22uUqU9y09liPBjvOfppI7SJN5ZCQ+OavNFtHDbyi+SUiHje/Y8iDnXH4momm2nDUzZni8xuzFJAylrhiF+1aSUK+k=
    wifi_password: AgBVcn1Yig7VEJ+ELHZORHeSsF3MibIGLnL+2UD/OCjDvXQrdQGLotq7PZ8bLjvv0vNKGfXm6VoNVLSXQkPa64VXckTtCxQEGLzcC+XmAGEBWqf1qEXuw7jfMjrhuPkEuY1nQFpAbt39O7YTycd1hWhSZuz8eBSxy0yHhQBJF2Gl+x0B5vo9Akv4+ZhQs2dz0A1ZfAs9hYfJBAXxuPEZ+VfLt7hD2LfhcHT1SY6uUPJxolPduFiOc1FnpVkbQS2cAx7fXJ/tpt+SdNc8FV8LlL43IEToOe+hCeHE14i7XM84BJt0ZT1BGr0JoV6NM9pGiIYG/FxEat6Qy+meY3fyo4vQPvfWBcBEiTZqrK0LsBmuG7OdHi89Oorp36pCjlPhqtLDC7oZTOxSKx6c3AfJob68eWXApu1THIDlFpPI6I8MzojRl7MFhgeWzpEWhFlxEyC96uZY/qnCApqbEkmMioT1uu8u+5BFM/Ne1lgB8dfGvRa62qqJAtf5vEBYpPHyH3m7wY25DPF3JEPdknh/mxI+p2XiDn75FRXww/j89IEFbUeOSei8ATiSGeRSatElFT448b9vRgN1X6mtodsRA22u3KbkEVrQqi7LSMTQCAZV5pMJARg2jZA2jqvG5fI2A8AWwcU9sosXLH+KHGQM+QW9n2REdYHJr0tN4UJELb9K6z5kaJhVpYlF3zZO8q3k5f2btNu9D1EmsLd82y52avEW5t7/
  template:
    data:
      secrets.yaml: |-
        wifi_ssid: WIFI-NOT
        wifi_password: "{{ index . "wifi_password" }}"
        wifi_domain: ".lan"
        api_password: "{{ index . "api_password" }}"
        ota_password: "{{ index . "ota_password" }}"
    metadata:
      name: secrets
      namespace: home-automation
      labels:
        app: esphome

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: esphome
  namespace: home-automation
  labels:
    app: esphome
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: esphome
          image: "container-image-registry.theautomation.nl/home-automation/esphome:latest@sha256:117479f1787335055306754f0336d30748fef50cf39fc49ff3bb8ebacb01f705"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6052
              protocol: TCP
          env:
            - name: "ESPHOME_DASHBOARD_USE_PING"
              value: "true"
          livenessProbe:
            tcpSocket:
              port: 6052
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6052
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 6052
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
      volumes:
        - name: secrets
          secret:
            secretName: secrets
      imagePullSecrets:
        - name: container-image-registry-credentials

---
kind: Service
apiVersion: v1
metadata:
  name: esphome
  namespace: home-automation
  labels:
    app: esphome
  annotations:
spec:
  selector:
    app: esphome
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 6052
      targetPort: 6052

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: esphome
  namespace: home-automation
  labels:
    app: esphome
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx-private
  rules:
    - host: esphome.k8s.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: esphome
                port:
                  number: 6052
