---
<<: !include common/.base.yaml

substitutions:
  device_name: basement-ventilation
  device_comment: "ESP32 with 4 relays for basement ventilation"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: esp-wrover-kit

button:
  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 20s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid

switch:
  - platform: gpio
    name: "${device_name}_sw_01"
    pin:
      number: 15
  - platform: gpio
    name: "${device_name}_sw_02"
    pin:
      number: 5
  - platform: gpio
    name: "${device_name}_sw_03"
    pin:
      number: 19
  - platform: gpio
    name: "${device_name}_sw_04"
    pin:
      number: 23
