---
<<: !include common/.base.yaml

substitutions:
  device_name: basement-wall-temperature
  device_comment:
    "ESP with dallas temperature sensor to measure the coldest place of the wall"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: esp32dev

button:
  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 20s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3
  - platform: dallas
    address: 0x0a3c01b55662b028
    name: ${device_name}

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid

dallas:
  - pin: GPIO27
