---
<<: !include common/base.yaml

substitutions:
  device_name: basement-wall-temperature
  device_comment:
    "ESP with dallas temperature sensor to measure the coldest place of the wall"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: esp32dev

button:
  - <<: !include common/button/restart.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml
  - platform: dallas
    address: 0x0a3c01b55662b028
    name: ${device_name}

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

dallas:
  - pin: GPIO27
