---
<<: !include common/base.yaml

substitutions:
  device_name: bathroom-sensors
  device_comment:
    "Humidity and temperature sensor for the bathroom"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp8266:
  board: d1_mini

button:
  - <<: !include common/button/restart.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml
  - platform: dht
    pin: D2
    temperature:
      name: ${device_name}_temperature
    humidity:
      name: ${device_name}_humidity
    update_interval: 60s
