---
<<: !include common/base.yaml

substitutions:
  device_name: childlock-kitchen
  device_comment: "ESP with relay to turn on or off a electromagnet lock"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp8266:
  board: nodemcuv2

button:
  - <<: !include common/button/restart.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

switch:
  - platform: gpio
    name: "${device_name}_switch"
    pin: D6
