---
substitutions:
  device_name: childlock_kitchen
  device_comment: "ESP with relay to turn on or off a electromagnet lock"

esphome:
  name: ${device_name}
  comment: ${device_comment}
  platform: ESP8266
  board: nodemcuv2

<<: !include common/wifi.yaml
<<: !include common/captive_portal.yaml
<<: !include common/logger.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include common/time.yaml
<<: !include common/uptime_sensor.yaml
<<: !include common/wifi_sensor.yaml
<<: !include common/version_sensor.yaml
<<: !include common/status_sensor.yaml
<<: !include common/restart_switch.yaml

switch:
  - platform: gpio
    name: "${device_name}_switch"
    pin: D6
