---
<<: !include common/.base.yaml

substitutions:
  device_name: childlock-kitchen
  device_comment: "ESP with relay to turn on or off a electromagnet lock"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp8266:
  board: nodemcuv2

button:
  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 20s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid

switch:
  - platform: gpio
    name: "${device_name}_switch"
    pin: D6
