---
<<: !include common/.base.yaml

substitutions:
  device_name: cv-closet
  device_comment:
    "Two relays for 12v for charging walltablet and 230v to turn on led spots in
    closet"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: esp32dev
  framework:
    type: arduino

button:
  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: status
    name: ${device_name}_status

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid

i2c:
  sda: 22
  scl: 23
  scan: false

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml
  - platform: bh1750
    name: "${device_name}_illuminance"
    address: 0x23
    update_interval: 1s

output:
  - platform: gpio
    pin:
      number: 18
      inverted: true
    id: gpio_18

switch:
  - platform: gpio
    name: "${device_name}_walltablet_charger"
    pin:
      number: 19
      inverted: true

light:
  - platform: binary
    name: "${device_name}"
    output: gpio_18
