---
substitutions:
  device_name: doorbell
  device_comment: "ESP-01S to turn on/off a analog doorbell chime or simulate buttonpress"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp8266:
  board: esp01_1m
  early_pin_init: false

<<: !include {file: common/api.yaml, vars: {reboot_timeout: "480min"}}
<<: !include common/wifi.yaml
<<: !include common/captive_portal.yaml
<<: !include common/logger.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include common/time.yaml
<<: !include common/uptime_sensor.yaml
<<: !include common/wifi_sensor.yaml
<<: !include common/version_sensor.yaml
<<: !include common/status_sensor.yaml
<<: !include common/restart_switch.yaml

globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: "true"

switch:
  # Switch to turn on/off the chime.
  - platform: gpio
    id: relay
    restore_mode: "RESTORE_DEFAULT_OFF"
    inverted: true
    name: ${device_name}_chime
    pin: GPIO0

  # Switch to turn on/off chime when
  # doorbell button is pushed.
  # It creates a "virtual" switch based
  # on a global variable.
  - platform: template
    name: ${device_name}_chime_active
    id: chime_active
    restore_mode: "RESTORE_DEFAULT_OFF"
    turn_on_action:
      - globals.set:
          id: chime
          value: "true"
    turn_off_action:
      - globals.set:
          id: chime
          value: "false"
    lambda: |-
      return id(chime);
# Binary sensor representing the
# Doorbell button push.
binary_sensor:
  - platform: gpio
    id: doorbell_button
    name: ${device_name}_button
    pin:
      # Connected to GPIO on the ESP-01S.
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: relay
