---
<<: !include common/.base.yaml

substitutions:
  device_name: smart-doorbell
  device_comment: "Zuidwijk smart-doorbell"

esphome:
  name: ${device_name}
  comment: ${device_comment}
  project:
    name: zuidwijk.smart-doorbell
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

button:
  - platform: restart
    name: ${device_name}_restart

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 20s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid

esp32_improv:
  authorizer: none

dashboard_import:
  package_import_url: github://zuidwijk/esphome-doorbell/smart-doorbell.yaml@main
  import_full_config: true

globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: "true"

switch:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: false
    name: "${device_name}_relay"
    id: relay
    internal: false
    icon: mdi:alarm-bell
  - platform: template
    name: ${device_name}_active
    id: chime_active
    restore_mode: disabled
    turn_on_action:
      - globals.set:
          id: chime
          value: "true"
    turn_off_action:
      - globals.set:
          id: chime
          value: "false"
    lambda: |-
      return id(chime);

binary_sensor:
  - platform: status
    name: ${device_name}_status
  - platform: gpio
    name: ${device_name}_button
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: false
    filters:
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
    on_release:
      - switch.turn_off: relay
