---
<<: !include common/.base.yaml

substitutions:
  device_name: weather-station
  device_comment:
    "This ESP detects illuminance, temperature, pressure and relative humidity"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: nodemcu-32s

button:
  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: status
    name: ${device_name}_status

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid

i2c:
  sda: 21
  scl: 22
  scan: false

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 20s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3
  - platform: bh1750
    name: "${device_name}_illuminance"
    address: 0x23
    update_interval: 2s
  # - platform: bme280
  #   temperature:
  #     name: "${device_name}_temperature"
  #     id: bme280_temperature
  #   pressure:
  #     name: "${device_name}_pressure"
  #     id: bme280_pressure
  #   humidity:
  #     name: "${device_name}_relative_humidity"
  #     id: bme280_humidity
  #   address: 0x76
  #   update_interval: 60s
