sensor:

  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 20s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3

text_sensor:

  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
    ssid:
      name: ${device_name}_wifi_ssid
    bssid:
      name: ${device_name}_wifi_bssid